version: "3"
services:
  rvx-builder:
    container_name: rvx-builder
    image: zoeyvid/docker-rv-rvx-builder
    restart: always
    ports:
      - "127.0.0.1:810:8000"
    environment:
      - "TZ=Europe/Berlin"
#      - "RV=true" # enable revanced instead of revanced extended, default false
  rv-builder:
    container_name: rv-builder
    image: zoeyvid/docker-rv-rvx-builder
    restart: always
    ports:
      - "127.0.0.1:820:8000"
    environment:
      - "TZ=Europe/Berlin"
      - "RV=true" # enable revanced instead of revanced extended, default false
